import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Hero from "../components/Hero";
import OutPartner from "../components/OutPartner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="font-poppins ">
      <Head>
        <title>Telaga Softwere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero Section */}
      <Hero />

      {/* Our Partner */}
      <OutPartner />

      <section className="h-screen bg-red-500"></section>
      <section className="h-screen"></section>
      <section className="h-screen bg-red-500"></section>
    </div>
  );
}
